#!/bin/sh
# License: CC0
# OpenWrt >= 19.07

BASE_URL="https://raw.githubusercontent.com/site-u2023/aios/main/"
BASE_DIR="/tmp/aios/"
SUPPORTED_VERSIONS="19 21 22 23 24 SN"

banner() {
    local lang="${SELECTED_LANGUAGE:-en}"
    local msg disclaimer

    if [ "$lang" = "en" ]; then
        msg="    Dedicated configuration software for OpenWrt.     "
        disclaimer="    Disclaimer: Use this script at your own risk.     "
        all_in_one="                  all in one scripts                  "
    elif [ "$lang" = "ja" ]; then
        msg="              OpenWrt 専用設定ソフトウェア              "
        disclaimer="      免責事項: 本スクリプトは自己責任でご使用下さい      "
        all_in_one="                オールインワンスクリプト                "
    fi
    echo -e "$(color "white"     "$msg")"
    echo -e "$(color "white"     "                                                      ")"
    echo -e "$(color "magenta"   "                    ii i                              ")"
    echo -e "$(color "blue"      "         aaaa      iii       oooo      sssss          ")"
    echo -e "$(color "cyan"      "            aa      ii      oo  oo    ss              ")"
    echo -e "$(color "green"     "         aaaaa      ii      oo  oo     sssss          ")"
    echo -e "$(color "yellow"    "        aa  aa      ii      oo  oo         ss         ")"
    echo -e "$(color "red"       "         aaaaa     iiii      oooo     ssssss          ")"
    echo -e "$(color "white"     "                                                      ")"
    echo -e "$(color "white"     "$all_in_one                                           ")"
    echo -e "$(color "white"     "                                                      ")"
    echo -e "$(color "red_white" "$disclaimer")"
}


delete_language() {
    if [ -e "${BASE_DIR}check_language" ]; then
        rm -rf "${BASE_DIR}check_language"
        echo "Initialized check_language."
    fi
}

make_directory() {
    if [ ! -d "$BASE_DIR" ]; then
        mkdir -p "$BASE_DIR" || { echo "Failed to create BASE_DIR"; exit 1; }
    fi
}

download_and_execute_common() {
    wget --no-check-certificate --quiet -O "${BASE_DIR%/}/common-functions.sh" "${BASE_URL}common-functions.sh" || {
        echo "Failed to download common-functions.sh"
        exit 1
    }
    source "${BASE_DIR%/}/common-functions.sh" || {
        echo "Failed to source common-functions.sh"
        exit 1
    }
}

download_openwrt_config() {
    wget --no-check-certificate --quiet -O "${BASE_DIR%/}/openwrt-config.sh" "${BASE_URL}openwrt-config.sh" || {
        echo "Failed to download openwrt-config.sh"
        exit 1
    }
}

execute_openwrt_config() {
    sh "${BASE_DIR%/}/openwrt-config.sh" || {
        echo "Failed to execute openwrt-config.sh"
        exit 1
    }
}

delete_language
make_directory
download_and_execute_common
check_common "$1"
download_openwrt_config
banner
execute_openwrt_config
